name: Harness static checks

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run static tests
        run: ./run-tests.sh
